name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Ensure this is the correct branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Hardcoded region

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381491983696.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t my-angular-app .

    - name: Tag Docker image
      run: |
        docker tag my-angular-app:latest 381491983696.dkr.ecr.us-east-1.amazonaws.com/my-angular-app:latest

    - name: Push Docker image
      run: |
        docker push 381491983696.dkr.ecr.us-east-1.amazonaws.com/my-angular-app:latest
